export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const MY_JOBS_LOADING = "MY_JOBS_LOADING";
export const MY_JOBS_SUCCESS = "MY_JOBS_SUCCESS";
export const MY_JOBS_ERROR = "MY_JOBS_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_JOB_LOADING = "CREATE_JOB_LOADING";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";
export const CLEAR_CREATE_JOB = "CLEAR_CREATE_JOB";

export const PUBLIC_JOBS_HOME_LOADING = "PUBLIC_JOBS_HOME_LOADING";
export const PUBLIC_JOBS_HOME_SUCCESS = "PUBLIC_JOBS_HOME_SUCCESS";
export const PUBLIC_JOBS_HOME_ERROR = "PUBLIC_JOBS_HOME_ERROR";

export const PUBLIC_JOB_DETAIL_LOADING = "PUBLIC_JOB_DETAIL_LOADING";
export const PUBLIC_JOB_DETAIL_SUCCESS = "PUBLIC_JOB_DETAIL_SUCCESS";
export const PUBLIC_JOB_DETAIL_ERROR = "PUBLIC_JOB_DETAIL_ERROR";

export const POST_APPLICATION_LOADING = "POST_APPLICATION_LOADING";
export const POST_APPLICATION_SUCCESS = "POST_APPLICATION_SUCCESS";
export const POST_APPLICATION_ERROR = "POST_APPLICATION_ERROR";

export const MY_APPLICATIONS_LOADING = "MY_APPLICATIONS_LOADING";
export const MY_APPLICATIONS_SUCCESS = "MY_APPLICATIONS_SUCCESS";
export const MY_APPLICATIONS_ERROR = "MY_APPLICATIONS_ERROR";
